### ISSUE TITLE
Unexpected Memory Leak

### ISSUE THREAD

**Issue by kazuser** [WladiD/AnyiQuack#2]
Hello there!

**Delphi 10.2.1** (25.0.27659.1188) + today's **AnyiQuack**:

1. Open project from \Examples\SlidingForm\
2. Add **ReportMemoryLeaksOnShutdown := True;** to **SlidingForm.dpr**:

> **program** SlidingForm;
> 
> **uses**
>   Forms,
>   Main **in** 'Main.pas' {Form1},
>   AQPControlAnimations **in** '..\..\AQPControlAnimations.pas',
>   AnyiQuack **in** '..\..\AnyiQuack.pas',
>   Vcl.Themes,
>   Vcl.Styles;
> 
> {$R *.res}
> 
> **begin**
>   ReportMemoryLeaksOnShutdown := True;
>   Application.Initialize;
>   Application.MainFormOnTaskbar := True;
>   Application.CreateForm(TForm1, Form1);
>   Application.Run;
> **end**.

3. Press **F9**
4. Click on the form...
5. Close application
6. Now check out the file in attach:
![uml](https://user-images.githubusercontent.com/3335273/33847591-3e7bd8f2-ded5-11e7-96e0-1752aaacf565.png)

Could you fix it please?

**Comment by WladiD** [comment]
Check out my last commit and let me know whether the leak is fixed...

**Comment by kazuser** [comment]
Yep, the problem has been solved, thank you!
