### ISSUE TITLE
Compilation error - [dcc32 Error] AnyiQuack.pas(2484): E2506 Method of parameterized type declared in interface section must not use local symbol 'PrimaryRetakeCheck'

### ISSUE THREAD

**Issue by mmarquee** [WladiD/AnyiQuack#3]
I have created an example application and it works OK, when I use the library in a 'real' application, I get several compilation errors

```
[dcc32 Error] AnyiQuack.pas(2484): E2506 Method of parameterized type declared in interface section must not use local symbol 'PrimaryRetakeCheck'
[dcc32 Error] AnyiQuack.pas(2713): E2250 There is no overloaded version of 'SpinUntil' that can be called with these arguments
[dcc32 Error] AnyiQuack.pas(2802): E2250 There is no overloaded version of 'SpinUntil' that can be called with these arguments
```

It might be that there are options that need to be set in the project - please can you advise?

**Comment by mmarquee** [comment]
This is with Delphi 10.2.2 btw

**Comment by WladiD** [comment]
Are you sure, that the right `Compile.inc` of AnyiQuack is used? To avoid conflicts AnyiQuack should resists in its own directory. 

Maybe you have an older version of AnyiQuack, which get referenced by the search path in Delphi or by the involved project?

**Comment by mmarquee** [comment]
I suspect that might be the issue - I have renamed it locally and will try again

**Comment by mmarquee** [comment]
I have change the Compile.inc file to prove that it is picking up the right one - changed the `RetakeFromGC` and the issue goes away - so it is picking it up. This fixes the immediate issue - not compiling,

**Comment by WladiD** [comment]
I'm unsure: Is this issue now solved for you?

As by design both variants (RetakeFromGC defined or not) should work. Possibly an other compiler option in your project introduces this behaviour. If you find something in this direction, let me know.

**Comment by WladiD** [comment]
As no further response: solved & closed
